config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :contents, controller: 'compose/contents'
    resources :compose_contents, controller: 'compose/contents'
    resources :menus
  end
  constraints(Spree::StaticPage) do
    get '/(*path)', :to => 'compose/contents#show', :as => 'static'
  end
end

app/models/spree/compose.rb
module Spree::Compose
  def self.table_name_prefix
    'spree_compose_'
  end
  def self.use_relative_model_naming?
    true
  end
end

app/models/spree/compose/assignment.rb
class Spree::Compose::Assignment < ActiveRecord::Base
  belongs_to :content
end

app/models/spree/compose/content.rb
class Spree::Compose::Content < ActiveRecord::Base

  has_many :assignments

  accepts_nested_attributes_for :assignments, allow_destroy: true, reject_if: proc { |attributes| attributes['zone'].blank? }

  scope :visible, -> { where(visible: true) }
  scope :pages, -> { where(content_type: 'Page') }
  scope :snippets, -> { where(content_type: 'Snippet') }
  scope :posts, -> { where(content_type: 'Post') }

  validates :slug, uniqueness: true

  translates :body, :slug, :description, :keywords, :title, fallbacks_for_empty_translations: true
  include SpreeI18n::Translatable

  # Allow to filter products through their translations, too
  def self.like_any(fields, values)
    translations = Spree::Compose::Content::Translation.arel_table

    joins(:translations).where(fields.map { |field|
      values.map { |value|
        translations[field].matches("%#{value}%").        # extension: match with translations under current locale
          or(arel_table[field].matches("%#{value}%"))     # compatible with original behaviour
      }.inject(:or)
    }.inject(:or).and(translations[:locale].eq(I18n.locale)))
  end

  def duplicate_extra(old_content)
    duplicate_translations(old_content)
  end

  def link
    slug.index('/') == 0 ? slug : '/' + slug
  end

  def is_page?
    content_type == "Page"
  end

end

app/models/spree/compose/menu.rb
class Spree::Compose::Menu < ActiveRecord::Base
  has_many :nav_items, class_name: 'Spree::Compose::NavItem'
  validates :name, presence: true, uniqueness: true
  accepts_nested_attributes_for :nav_items, allow_destroy: true
end

app/models/spree/compose/nav_item.rb
class Spree::Compose::NavItem < ActiveRecord::Base
  belongs_to :menu, class_name: 'Spree::Compose::Menu'
end

app/controllers/spree/admin/compose/contents_controller.rb
class Spree::Admin::Compose::ContentsController < Spree::Admin::BaseController
  before_action :set_content, only: [:edit, :update, :destroy]
    
  def index
    @contents = Spree::Compose::Content.all
  end

  def new
    @content = Spree::Compose::Content.new
    @content.assignments.build
  end
  
  def edit
    @content.assignments.build
  end

  def create
    @content = Spree::Compose::Content.new(permitted_resource_params)
    if @content.save
      redirect_to admin_contents_path, success: "Save new #{@content.content_type}"
    else
      render :new
    end
  end

  def update
    @content.update!(permitted_resource_params)
    redirect_to admin_contents_path, success: "Updated #{@content.content_type}"
  end

  def destroy
    @content.destroy
    redirect_to admin_contents_path, notice: "Removed the #{@content.content_type}"
  end

  private

  def set_content
    @content = Spree::Compose::Content.find(params[:id])
  end

  def permitted_resource_params
    params.require(:content).permit(
      :body, :slug, :subject_id, :content_type, :ancestry, :position, :description, :keywords, :title, :visible,
      translations_attributes: [:id, :locale, :value, :body, :slug, :description, :keywords, :title],
      assignments_attributes: [:id, :content_id, :path, :zone, :position, :_destroy]
    )
  end
end

app/controllers/spree/admin/menus_controller.rb
class Spree::Admin::MenusController < Spree::Admin::BaseController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @menus = Spree::Compose::Menu.all
  end

  def show
    @menus = Spree::Compose::Menu.all
    @pages = Spree::Compose::Content.where(content_type: "Page")
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  def new
    @menu = Spree::Compose::Menu.new
  end

  def edit
  end

  def create
    @menu = Spree::Compose::Menu.new(resource_params)

    if @menu.save
      redirect_to admin_menu_path(@menu), notice: 'Menu was successfully created.'
    else
      render :new
    end
  end

  def update
    if @menu.update(resource_params)
      redirect_to admin_menu_path(@menu), notice: 'Menu was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @menu.destroy
    redirect_to admin_menus_url, notice: 'Menu was successfully destroyed.'
  end

  private

  def set_resource
    @menu = Spree::Compose::Menu.find(params[:id])
  end

  def resource_params
    params.require(:menu).permit(:name)
  end
  
end

app/controllers/spree/admin/translations_controller_decorator.rb
Spree::Admin::TranslationsController.class_eval do

  def klass
    klass_name = params[:resource] == 'compose_contents' ? 'Compose::Content' : params[:resource].classify
    @klass ||= "Spree::#{klass_name.classify}".constantize
  end

end

app/controllers/spree/compose/contents_controller.rb
class Spree::Compose::ContentsController < Spree::StoreController

  # Don't serve local files or static assets
  before_action { render_404 if params[:path] =~ /(\.|\\)/ }
  
  respond_to :html

  def show
    path = "/#{params[:path]}"
    @content = Spree::Compose::Content.visible.find_by_slug(path)
    if @content
      render :show
    else
      render_404
    end
  end
  
end

app/helpers/spree/compose/application_helper.rb
module Spree
  module Compose
    module ApplicationHelper
      
      def zone_render(identifier = nil)
        assigment = Spree::Compose::Assignment.where(path: [request.path, nil, ''], zone: identifier).joins(:content)
        if assigment.exists?
          raw assigment.first.content.body
        end
      end

    end
  end
end

app/views/spree/admin/compose/contents/_form.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @content } %>

<%= f.field_container :visible, class: ['form-group'] do %>
  <label class="checkbox-inline">
    <%= f.check_box :visible, class: 'checkbox visible' %> <%= Spree.t(:visible, scope: :contents) %>
  </label>
<% end %>

<%= f.field_container :content_type, class: ['form-group'] do %>
  <%= f.label :content_type, Spree.t(:content_type, scope: :contents) %> <span class="required">*</span>
  <%= f.select :content_type, ["Page", "Snippet", "Post", "Layout"], {}, { class: "form-control" } %>
<% end %>

<%= f.field_container :slug, class: ['form-group','page-attribute'] do %>
  <%= f.label :slug, Spree.t(:slug, scope: :contents) %> <span class="required">*</span>
  <%= f.text_field :slug, class: 'form-control slug' %>
  <%= f.error_message_on :slug %>
<% end %>

<%= f.field_container :title, class: ['form-group','page-attribute'] do %>
  <%= f.label :title, Spree.t(:title, scope: :contents) %> <span class="required">*</span>
  <%= f.text_field :title, class: 'form-control title' %>
  <%= f.error_message_on :title %>
<% end %>  

<%= f.field_container :description, class: ['form-group','page-attribute'] do %>
  <%= f.label :description, Spree.t(:description, scope: :contents) %> <span class="required">*</span>
  <%= f.text_field :description, class: 'form-control description' %>
  <%= f.error_message_on :description %>
<% end %>

<%= f.field_container :keywords, class: ['form-group','page-attribute'] do %>
  <%= f.label :keywords, Spree.t(:keywords, scope: :contents) %> <span class="required">*</span>
  <%= f.text_field :keywords, class: 'form-control keywords' %>
  <%= f.error_message_on :keywords %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">Where's it go? (Page path &amp; Zone)</div>
  <div class="panel-body">
    <%= f.fields_for :assignments, f.object.assignments do |a| %>
      <div class="form-group row">
        <%= a.label :path, Spree.t(:path, scope: :contents), class: 'col-md-1 control-label' %>
        <div class="col-md-4">  
          <%= a.text_field :path, class: 'form-control path' %>
        </div>
        <%= a.label :zone, Spree.t(:zone, scope: :contents), class: 'col-md-1 control-label' %>
        <div class="col-md-4">  
          <%= a.text_field :zone, class: 'form-control zone' %>
        </div>
        <div class="col-md-2">
          Delete: <%= a.check_box :_destroy %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= f.field_container :subject_body, class: ['form-group'] do %>
  <%= f.label :body, Spree.t(:body, scope: :contents) %> <span class="required">*</span>
  <%= f.error_message_on :body %>
  <%= f.text_area :body, class: 'form-control body summernote' %>
<% end %>

<script>
  <% inital_attr = @content.content_type.nil? ? "Page" : "#{@content.content_type}" %>
  var initalAttr = "<%= inital_attr %>";
  var attrs = {
    Page: {
      hide: ".partial-attribute",
      show: ".page-attribute"
    }, 
    Snippet: {
      hide: ".page-attribute",
      show: ".partial-attribute"
    }
  };
  var displayFields = function(content_type) {
    $(attrs[content_type].hide).hide();
    $(attrs[content_type].show).show();
  };
  displayFields(initalAttr);
  $('#content_content_type').on('change', function(e){
    displayFields(this.value);
  });
</script>

app/views/spree/admin/compose/contents/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t :edit, scope: :contents %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'translate', nil, admin_translations_path('compose_contents', @content.id), title: Spree.t(:'i18n.translations'), class: 'btn btn-sm btn-primary' %>
<% end if can?(:translate, Spree::Compose::Content) %>

<%= form_for [:admin, @content], :html => { :multipart => true } do |f| %>
  <%= render partial: 'form', :locals => { :f => f } %>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.edit'), 'ok', 'submit', {class: 'btn-success'} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_contents_url, :icon => 'remove' %>
  </div>
<% end %>

app/views/spree/admin/compose/contents/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t :name, scope: :contents %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:create, scope: :contents), 
        new_admin_content_url, 
        { :class => "btn-success", :icon => 'add', :id => 'admin_new_content' } %>
<% end if can?(:create, Spree::Compose::Content) %>

<% if @contents.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:everything, scope: :contents) %></th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @contents.each do |content| %>
      <tr <%== "style='color: red;'" if !content.visible %> id="<%= spree_dom_id content %>" data-hook="admin_contents_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= content.title %></td>
        <td class="actions actions-3 text-right" data-hook="admin_content_index_row_actions">
          
          <%= link_to_with_icon('delete', nil, admin_content_path(content),
                title: Spree.t(:delete),
                data: { confirm: Spree.t(:are_you_sure), action: 'remove' }, 
                class: "btn btn-danger btn-sm delete-resource icon-link with-tip action-delete") if can?(:destroy, content) %>

          <%= link_to_with_icon('edit', nil, edit_admin_content_path(content),
                title: Spree.t(:edit),
                data: { action: 'edit' }, 
                class: "btn btn-primary btn-sm icon-link with-tip action-edit") if can?(:edit, content)  %>

          <%= link_to_with_icon('link', nil, content.link,
                title: Spree.t(:visit_page, scope: :contents) + ' ' + content.link,
                target: "_blank", 
                class: "btn btn-primary btn-sm icon-link with-tip action-edit") if content.is_page? %>

          <%= link_to_with_icon('translate', nil, admin_translations_path('compose_contents', content.id), 
                title: Spree.t(:'i18n.translations'), 
                class: 'btn btn-sm btn-primary') if can?(:translate, Spree::Compose::Content)  %>

        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/compose/contents/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t :new, scope: :contents %>
<% end %>

<%= form_for [:admin, @content], :html => { :multipart => true } do |f| %>
  <%= render partial: 'form', :locals => { :f => f } %>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.create'), 'ok', 'submit', {class: 'btn-success'} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_contents_url, :icon => 'remove' %>
  </div>
<% end %>

app/views/spree/admin/menus/_form.html.erb
<%= form_for([:admin, @menu]) do |f| %>
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @menu } %>

  <%= f.field_container :name, class: ['form-group'] do %>
    <%= f.label :name, Spree.t(:name, scope: :menu) %> <span class="required">*</span>
    <%= f.text_field :name, class: 'form-control name' %>
    <%= f.error_message_on :name %>
  <% end %>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.create'), 'ok', 'submit', {class: 'btn-success'} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_menus_url, :icon => 'remove' %>
  </div>
<% end %>

app/views/spree/admin/menus/_panel_freeform.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="heading-freeform">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#nav-panels" href="#collapse-freeform" aria-expanded="false" aria-controls="collapse-freeform">
        Free Form
      </a>
    </h4>
  </div>
  <div id="collapse-freeform" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-freeform">
    <div class="panel-body">
      <form class="form-horizontal">
        <div class="form-group">
          <label class="col-sm-2 control-label">Title</label>
          <div class="col-sm-10">
            <input type="text" class="form-input" />
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-sm-2 control-label">URL</label>
          <div class="col-sm-10">
            <input type="text" class="form-input" />
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/spree/admin/menus/_panel_pages.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="heading-pages">
    <h4 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#nav-panels" href="#collapse-pages" aria-expanded="false" aria-controls="collapse-pages">
        Pages
      </a>
    </h4>
  </div>
  <div id="collapse-pages" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-pages">
    <div class="panel-body">
      <% if @pages.any? %>
        <ul class="list-unstyled">
        <% @pages.each do |page| %>
          <li><%= check_box_tag 'page' %> <%= page.title %> </li>
        <% end %>
        </ul>
      <% else %>
        <p>You don't have any visible pages that can be used in a menu yet...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/menus/_panel_taxons.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="heading-taxons">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#nav-panels" href="#collapse-taxons" aria-expanded="true" aria-controls="collapse-taxons">
        Taxonomies
      </a>
    </h4>
  </div>
  <div id="collapse-taxons" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-taxons">
    <div class="panel-body">
      <% if @taxonomies.any? %>
        <ul class="list-unstyled">
        <% @taxonomies.each do |taxonomy| %>
          <li><%= check_box_tag 'taxonomy' %> <%= taxonomy.name %> </li>
        <% end %>
        </ul>
      <% else %>
        <p>You don't have any visible taxonomies that can be used in a menu yet...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/menus/edit.html.erb
<h1>Editing Admin Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', admin_menus_path %>

app/views/spree/admin/menus/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t :title, scope: :menus %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:create), 
        new_admin_menu_path, 
        { :class => "btn-success", :icon => 'add' } %>
<% end if can?(:create, Spree::Compose::Menu) %>

<% if @menus.any? %>
  <table class="table">
    <thead>
      <tr data-hook="admin_menus_index_headers">
        <th><%= Spree.t(:title, scope: :menus) %></th>
        <th data-hook="admin_menus_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @menus.each do |menu| %>
      <tr id="<%= spree_dom_id menu %>" data-hook="admin_menus_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= link_to menu.name, admin_menu_path(menu) %></td>
        <td class="actions actions-3 text-right" data-hook="admin_menu_index_row_actions">
          
          <%= link_to_with_icon('delete', nil, admin_menu_path(menu),
                title: Spree.t(:delete),
                data: { confirm: Spree.t(:are_you_sure), action: 'remove' }, 
                class: "btn btn-danger btn-sm delete-resource icon-link with-tip action-delete") if can?(:destroy, menu) %>

          <%= link_to_with_icon('edit', nil, admin_menu_path(menu),
                title: Spree.t(:edit),
                data: { action: 'edit' }, 
                class: "btn btn-primary btn-sm icon-link with-tip action-edit") if can?(:edit, menu)  %>

        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/menus/new.html.erb
<h1>New Admin Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_menus_path %>

app/views/spree/admin/shared/_content_tabs.html.erb
<% content_for :page_title do %>
  <%= @compose_content.slug %>
<% end %>

app/views/spree/admin/shared/sub_menu/_contents.html.erb
<ul id="sidebar-content" class="collapse nav nav-pills nav-stacked" data-hook="admin_content_sub_tabs">
  <%= tab :contents %>
</ul>

app/views/spree/admin/translations/compose_content.html.erb
<%= render 'spree/admin/shared/content_tabs', current: 'Translations' %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: Spree::Compose::Content.model_name.human), admin_contents_path, class: 'btn-primary', icon: 'arrow-left' %>
<% end %>

<%= render 'form' %>

app/views/spree/compose/contents/show.html.erb
<% content_for :head do -%>
  <meta name="title" content="<%=@content.title%>">
<% end -%>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= raw @content.body %>
    </div>
  </div>
</div>